// SPDX-License-Identifier: Elastic-2.0

package main

import (
	"os"
	"path/filepath"
	"testing"
)

// writeIn writes a file under a subdirectory of root, creating the directory.
func writeIn(t *testing.T, root, dir, name, body string) {
	t.Helper()
	full := filepath.Join(root, dir)
	if err := os.MkdirAll(full, 0o755); err != nil {
		t.Fatalf("creating %s: %v", dir, err)
	}
	write(t, full, name, body)
}

func TestCollectUnlicensedFindsFilesWithoutAnSPDXHeader(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	write(t, root, "licensed.go", "// SPDX-License-Identifier: Elastic-2.0\n\npackage x\n")
	write(t, root, "bare.go", "package x\n")
	write(t, root, "licensed.ts", "// SPDX-License-Identifier: AGPL-3.0-or-later\n\nexport const a = 1\n")
	write(t, root, "bare.tsx", "export const b = 2\n")
	write(t, root, "generated.go", "// Code generated by hand. DO NOT EDIT.\n\npackage x\n")
	write(t, root, "README.md", "no header is expected here\n")
	writeIn(t, root, "gql", "graphql.ts", "/* eslint-disable */\nexport type A = string\n")
	writeIn(t, root, "node_modules/pkg", "index.ts", "export const c = 3\n")
	writeIn(t, root, "dist", "bundle.js", "export const d = 4\n")

	unlicensed, err := collectUnlicensed(root)

	if err != nil {
		t.Fatalf("collectUnlicensed() error = %v, want nil", err)
	}
	want := map[string]bool{"bare.go": true, "bare.tsx": true}
	if len(unlicensed) != len(want) {
		t.Fatalf("unlicensed = %v, want exactly %v", unlicensed, want)
	}
	for _, path := range unlicensed {
		if !want[filepath.Base(path)] {
			t.Errorf("unexpected unlicensed file %q, want only %v", path, want)
		}
	}
}

func TestCollectUnlicensedReportsAMissingRoot(t *testing.T) {
	t.Parallel()

	_, err := collectUnlicensed(filepath.Join(t.TempDir(), "absent"))

	if err == nil {
		t.Fatal("collectUnlicensed() error = nil, want the missing root reported")
	}
}

func TestCarriesLicenseReportsAnUnreadableFile(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	write(t, root, "locked.ts", "export const a = 1\n")
	locked := filepath.Join(root, "locked.ts")
	if err := os.Chmod(locked, 0o000); err != nil {
		t.Fatalf("locking the file: %v", err)
	}

	_, err := carriesLicense(locked)

	if err == nil {
		t.Fatal("carriesLicense() error = nil, want the unreadable file reported")
	}
}

func TestCarriesLicenseReportsAReadFailure(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	if err := os.Mkdir(filepath.Join(root, "shaped.ts"), 0o755); err != nil {
		t.Fatalf("creating the directory: %v", err)
	}

	_, err := carriesLicense(filepath.Join(root, "shaped.ts"))

	if err == nil {
		t.Fatal("carriesLicense() error = nil, want the read failure reported")
	}
}

func TestRunReportsAnUnreadableFile(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	write(t, root, "locked.ts", "export const a = 1\n")
	if err := os.Chmod(filepath.Join(root, "locked.ts"), 0o000); err != nil {
		t.Fatalf("locking the file: %v", err)
	}

	err := run(root, os.Stderr)

	if err == nil {
		t.Fatal("run() error = nil, want the unreadable file reported")
	}
}

func TestRunReportsAnUnlicensedFile(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	write(t, root, "documented.go",
		"// SPDX-License-Identifier: Elastic-2.0\n\npackage x\n\n// Ok is documented.\nfunc Ok() {}\n")
	write(t, root, "bare.ts", "export const a = 1\n")

	err := run(root, os.Stderr)

	if err == nil {
		t.Fatal("run() error = nil, want the missing license header reported")
	}
}
