// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreApiToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	TokenHash  string
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
	Scopes     string
	ExpiresAt  pgtype.Timestamptz
	TenantID   uuid.UUID
}

type CoreContact struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	TenantID  uuid.UUID
}

type CoreContactIdentity struct {
	ID          uuid.UUID
	ContactID   uuid.UUID
	Channel     string
	Identifier  string
	DisplayName string
	CreatedAt   time.Time
	TenantID    uuid.UUID
}

type CoreTask struct {
	ID            uuid.UUID
	AssigneeID    uuid.UUID
	ContactID     pgtype.UUID
	Title         string
	Status        string
	Priority      int16
	DueOn         time.Time
	OriginSource  pgtype.Text
	OriginEventID pgtype.UUID
	CreatedAt     time.Time
	TenantID      uuid.UUID
}

type CoreTenant struct {
	ID            uuid.UUID
	Name          string
	CreatedAt     time.Time
	DeactivatedAt pgtype.Timestamptz
}

type CoreTenantMember struct {
	UserID    uuid.UUID
	TenantID  uuid.UUID
	CreatedAt time.Time
}

type CoreUserSetting struct {
	UserID    uuid.UUID
	Key       string
	Value     string
	CreatedAt time.Time
	TenantID  uuid.UUID
}

type CoreWebhookDelivery struct {
	ID             uuid.UUID
	SubscriptionID uuid.UUID
	EventID        uuid.UUID
	EventName      string
	Payload        string
	Attempts       int32
	DeliverAfter   time.Time
	Status         string
	LastError      pgtype.Text
	CreatedAt      time.Time
	TenantID       uuid.UUID
}

type CoreWebhookSubscription struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Url       string
	Events    []string
	Secret    string
	CreatedAt time.Time
	TenantID  uuid.UUID
}
