// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type CoreContact struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type CoreContactIdentity struct {
	ID          uuid.UUID
	ContactID   uuid.UUID
	Channel     string
	Identifier  string
	DisplayName string
	CreatedAt   time.Time
}
