// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createContact = `-- name: CreateContact :exec

INSERT INTO core.contacts (id, name, created_at)
VALUES ($1, $2, $3)
`

type CreateContactParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

// SPDX-License-Identifier: Elastic-2.0
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) error {
	_, err := q.db.Exec(ctx, createContact, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const createIdentity = `-- name: CreateIdentity :execrows
INSERT INTO core.contact_identities (id, contact_id, channel, identifier, display_name, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (channel, identifier) DO NOTHING
`

type CreateIdentityParams struct {
	ID          uuid.UUID
	ContactID   uuid.UUID
	Channel     string
	Identifier  string
	DisplayName string
	CreatedAt   time.Time
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, createIdentity,
		arg.ID,
		arg.ContactID,
		arg.Channel,
		arg.Identifier,
		arg.DisplayName,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContact = `-- name: GetContact :one
SELECT id, name, created_at
FROM core.contacts
WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (CoreContact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i CoreContact
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
SELECT id, contact_id, channel, identifier, display_name, created_at
FROM core.contact_identities
WHERE channel = $1 AND identifier = $2
`

type GetIdentityParams struct {
	Channel    string
	Identifier string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (CoreContactIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Channel, arg.Identifier)
	var i CoreContactIdentity
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Channel,
		&i.Identifier,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const listContactIdentities = `-- name: ListContactIdentities :many
SELECT id, contact_id, channel, identifier, display_name, created_at
FROM core.contact_identities
WHERE contact_id = $1
ORDER BY channel, identifier
`

func (q *Queries) ListContactIdentities(ctx context.Context, contactID uuid.UUID) ([]CoreContactIdentity, error) {
	rows, err := q.db.Query(ctx, listContactIdentities, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContactIdentity
	for rows.Next() {
		var i CoreContactIdentity
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Channel,
			&i.Identifier,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, name, created_at
FROM core.contacts c
WHERE (c.name, c.id) > ($1::text, $2::uuid)
    AND ($3::text = '' OR c.name ILIKE '%' || $3 || '%'
        OR EXISTS (
            SELECT 1 FROM core.contact_identities i
            WHERE i.contact_id = c.id
                AND (i.display_name ILIKE '%' || $3 || '%'
                    OR ($4::text <> '' AND i.identifier LIKE '%' || $4 || '%'))))
ORDER BY c.name, c.id
LIMIT $5
`

type ListContactsParams struct {
	AfterName string
	AfterID   uuid.UUID
	Query     string
	Digits    string
	RowLimit  int32
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]CoreContact, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.AfterName,
		arg.AfterID,
		arg.Query,
		arg.Digits,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContact
	for rows.Next() {
		var i CoreContact
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactName = `-- name: UpdateContactName :one
UPDATE core.contacts SET name = $2 WHERE id = $1
RETURNING id, name, created_at
`

type UpdateContactNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateContactName(ctx context.Context, arg UpdateContactNameParams) (CoreContact, error) {
	row := q.db.QueryRow(ctx, updateContactName, arg.ID, arg.Name)
	var i CoreContact
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
