// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addIdentity = `-- name: AddIdentity :one
WITH inserted AS (
    INSERT INTO core.contact_identities (id, contact_id, channel, identifier, display_name, created_at)
    VALUES ($1, $2, $3, $4, $5, $6)
    ON CONFLICT (channel, identifier) DO NOTHING
    RETURNING contact_id
)
SELECT contact_id AS owner_id, TRUE AS created FROM inserted
UNION ALL
SELECT contact_id, FALSE
FROM core.contact_identities
WHERE channel = $3 AND identifier = $4
    AND NOT EXISTS (SELECT 1 FROM inserted)
`

type AddIdentityParams struct {
	ID          uuid.UUID
	ContactID   uuid.UUID
	Channel     string
	Identifier  string
	DisplayName string
	CreatedAt   time.Time
}

type AddIdentityRow struct {
	OwnerID uuid.UUID
	Created bool
}

func (q *Queries) AddIdentity(ctx context.Context, arg AddIdentityParams) (AddIdentityRow, error) {
	row := q.db.QueryRow(ctx, addIdentity,
		arg.ID,
		arg.ContactID,
		arg.Channel,
		arg.Identifier,
		arg.DisplayName,
		arg.CreatedAt,
	)
	var i AddIdentityRow
	err := row.Scan(&i.OwnerID, &i.Created)
	return i, err
}

const claimWebhookDeliveries = `-- name: ClaimWebhookDeliveries :many
WITH claimed AS (
    UPDATE core.webhook_deliveries
    SET attempts = attempts + 1, deliver_after = $1::timestamptz
    WHERE id IN (
        SELECT d.id
        FROM core.webhook_deliveries d
        WHERE d.status = 'pending' AND d.deliver_after <= $2::timestamptz
        ORDER BY d.deliver_after, d.id
        LIMIT $3
        FOR UPDATE SKIP LOCKED
    )
    RETURNING id, subscription_id, event_id, event_name, payload,
        attempts, deliver_after, status, last_error, created_at
)
SELECT c.id, c.subscription_id, c.event_id, c.event_name, c.payload,
    c.attempts, c.deliver_after, c.status, c.last_error, c.created_at,
    s.url, s.secret
FROM claimed c
JOIN core.webhook_subscriptions s ON s.id = c.subscription_id
`

type ClaimWebhookDeliveriesParams struct {
	Lease    time.Time
	Due      time.Time
	RowLimit int32
}

type ClaimWebhookDeliveriesRow struct {
	ID             uuid.UUID
	SubscriptionID uuid.UUID
	EventID        uuid.UUID
	EventName      string
	Payload        string
	Attempts       int32
	DeliverAfter   time.Time
	Status         string
	LastError      pgtype.Text
	CreatedAt      time.Time
	Url            string
	Secret         string
}

func (q *Queries) ClaimWebhookDeliveries(ctx context.Context, arg ClaimWebhookDeliveriesParams) ([]ClaimWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveries, arg.Lease, arg.Due, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimWebhookDeliveriesRow
	for rows.Next() {
		var i ClaimWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventID,
			&i.EventName,
			&i.Payload,
			&i.Attempts,
			&i.DeliverAfter,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.Url,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO core.api_tokens (id, user_id, name, token_hash, created_at, last_used_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAPITokenParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	TokenHash  string
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.Exec(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}

const createContact = `-- name: CreateContact :exec

INSERT INTO core.contacts (id, name, created_at)
VALUES ($1, $2, $3)
`

type CreateContactParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

// SPDX-License-Identifier: Elastic-2.0
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) error {
	_, err := q.db.Exec(ctx, createContact, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO core.tasks (id, assignee_id, contact_id, title, status, priority, due_on,
    origin_source, origin_event_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10)
ON CONFLICT (assignee_id, origin_source, origin_event_id) WHERE origin_event_id IS NOT NULL
DO UPDATE SET id = core.tasks.id
RETURNING id, assignee_id, contact_id, title, status, priority, due_on,
    origin_source, origin_event_id, created_at, (xmax = 0) AS created
`

type CreateTaskParams struct {
	ID            uuid.UUID
	AssigneeID    uuid.UUID
	ContactID     pgtype.UUID
	Title         string
	Status        string
	Priority      int16
	DueOn         time.Time
	OriginSource  pgtype.Text
	OriginEventID pgtype.UUID
	CreatedAt     time.Time
}

type CreateTaskRow struct {
	ID            uuid.UUID
	AssigneeID    uuid.UUID
	ContactID     pgtype.UUID
	Title         string
	Status        string
	Priority      int16
	DueOn         time.Time
	OriginSource  pgtype.Text
	OriginEventID pgtype.UUID
	CreatedAt     time.Time
	Created       bool
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.AssigneeID,
		arg.ContactID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.DueOn,
		arg.OriginSource,
		arg.OriginEventID,
		arg.CreatedAt,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.AssigneeID,
		&i.ContactID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.DueOn,
		&i.OriginSource,
		&i.OriginEventID,
		&i.CreatedAt,
		&i.Created,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :exec
INSERT INTO core.webhook_deliveries (
    id, subscription_id, event_id, event_name, payload,
    attempts, deliver_after, status, last_error, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateWebhookDeliveryParams struct {
	ID             uuid.UUID
	SubscriptionID uuid.UUID
	EventID        uuid.UUID
	EventName      string
	Payload        string
	Attempts       int32
	DeliverAfter   time.Time
	Status         string
	LastError      pgtype.Text
	CreatedAt      time.Time
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, createWebhookDelivery,
		arg.ID,
		arg.SubscriptionID,
		arg.EventID,
		arg.EventName,
		arg.Payload,
		arg.Attempts,
		arg.DeliverAfter,
		arg.Status,
		arg.LastError,
		arg.CreatedAt,
	)
	return err
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :exec
INSERT INTO core.webhook_subscriptions (id, user_id, url, events, secret, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebhookSubscriptionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Url       string
	Events    []string
	Secret    string
	CreatedAt time.Time
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createWebhookSubscription,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.Events,
		arg.Secret,
		arg.CreatedAt,
	)
	return err
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
DELETE FROM core.contact_identities
WHERE id = $1 AND contact_id = $2
`

type DeleteIdentityParams struct {
	ID        uuid.UUID
	ContactID uuid.UUID
}

func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentity, arg.ID, arg.ContactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :execrows
DELETE FROM core.webhook_subscriptions
WHERE id = $1 AND user_id = $2
`

type DeleteWebhookSubscriptionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, arg DeleteWebhookSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookSubscription, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, created_at, last_used_at
FROM core.api_tokens
WHERE token_hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (CoreApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i CoreApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, name, created_at
FROM core.contacts
WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (CoreContact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i CoreContact
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
SELECT id, contact_id, channel, identifier, display_name, created_at
FROM core.contact_identities
WHERE channel = $1 AND identifier = $2
`

type GetIdentityParams struct {
	Channel    string
	Identifier string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (CoreContactIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Channel, arg.Identifier)
	var i CoreContactIdentity
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Channel,
		&i.Identifier,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, assignee_id, contact_id, title, status, priority, due_on,
    origin_source, origin_event_id, created_at
FROM core.tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (CoreTask, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i CoreTask
	err := row.Scan(
		&i.ID,
		&i.AssigneeID,
		&i.ContactID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.DueOn,
		&i.OriginSource,
		&i.OriginEventID,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokensForUser = `-- name: ListAPITokensForUser :many
SELECT id, user_id, name, token_hash, created_at, last_used_at
FROM core.api_tokens
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPITokensForUser(ctx context.Context, userID uuid.UUID) ([]CoreApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreApiToken
	for rows.Next() {
		var i CoreApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactIdentities = `-- name: ListContactIdentities :many
SELECT id, contact_id, channel, identifier, display_name, created_at
FROM core.contact_identities
WHERE contact_id = $1
ORDER BY channel, identifier
`

func (q *Queries) ListContactIdentities(ctx context.Context, contactID uuid.UUID) ([]CoreContactIdentity, error) {
	rows, err := q.db.Query(ctx, listContactIdentities, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContactIdentity
	for rows.Next() {
		var i CoreContactIdentity
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Channel,
			&i.Identifier,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, name, created_at
FROM core.contacts c
WHERE (c.name, c.id) > ($1::text, $2::uuid)
    AND ($3::text = '' OR c.name ILIKE '%' || $3 || '%'
        OR EXISTS (
            SELECT 1 FROM core.contact_identities i
            WHERE i.contact_id = c.id
                AND (i.display_name ILIKE '%' || $3 || '%'
                    OR ($4::text <> '' AND i.identifier LIKE '%' || $4 || '%'))))
ORDER BY c.name, c.id
LIMIT $5
`

type ListContactsParams struct {
	AfterName string
	AfterID   uuid.UUID
	Query     string
	Digits    string
	RowLimit  int32
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]CoreContact, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.AfterName,
		arg.AfterID,
		arg.Query,
		arg.Digits,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContact
	for rows.Next() {
		var i CoreContact
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByIDs = `-- name: ListContactsByIDs :many
SELECT id, name, created_at
FROM core.contacts
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListContactsByIDs(ctx context.Context, ids []uuid.UUID) ([]CoreContact, error) {
	rows, err := q.db.Query(ctx, listContactsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContact
	for rows.Next() {
		var i CoreContact
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksDueBefore = `-- name: ListTasksDueBefore :many
SELECT id, assignee_id, contact_id, title, status, priority, due_on,
    origin_source, origin_event_id, created_at
FROM core.tasks t
WHERE t.assignee_id = $1::uuid
    AND t.due_on < $2::date
    AND ($3::text = 'all' OR t.status = $3::text)
    AND (t.due_on, t.id) > ($4::date, $5::uuid)
ORDER BY t.due_on, t.id
LIMIT $6
`

type ListTasksDueBeforeParams struct {
	AssigneeID uuid.UUID
	DueBefore  time.Time
	Status     string
	AfterDueOn time.Time
	AfterID    uuid.UUID
	RowLimit   int32
}

func (q *Queries) ListTasksDueBefore(ctx context.Context, arg ListTasksDueBeforeParams) ([]CoreTask, error) {
	rows, err := q.db.Query(ctx, listTasksDueBefore,
		arg.AssigneeID,
		arg.DueBefore,
		arg.Status,
		arg.AfterDueOn,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreTask
	for rows.Next() {
		var i CoreTask
		if err := rows.Scan(
			&i.ID,
			&i.AssigneeID,
			&i.ContactID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.DueOn,
			&i.OriginSource,
			&i.OriginEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForContact = `-- name: ListTasksForContact :many
SELECT id, assignee_id, contact_id, title, status, priority, due_on,
    origin_source, origin_event_id, created_at
FROM core.tasks t
WHERE t.contact_id = $1::uuid
    AND ($2::text = 'all' OR t.status = $2::text)
    AND (t.due_on, t.id) > ($3::date, $4::uuid)
ORDER BY t.due_on, t.id
LIMIT $5
`

type ListTasksForContactParams struct {
	ContactID  uuid.UUID
	Status     string
	AfterDueOn time.Time
	AfterID    uuid.UUID
	RowLimit   int32
}

func (q *Queries) ListTasksForContact(ctx context.Context, arg ListTasksForContactParams) ([]CoreTask, error) {
	rows, err := q.db.Query(ctx, listTasksForContact,
		arg.ContactID,
		arg.Status,
		arg.AfterDueOn,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreTask
	for rows.Next() {
		var i CoreTask
		if err := rows.Scan(
			&i.ID,
			&i.AssigneeID,
			&i.ContactID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.DueOn,
			&i.OriginSource,
			&i.OriginEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForDay = `-- name: ListTasksForDay :many
SELECT id, assignee_id, contact_id, title, status, priority, due_on,
    origin_source, origin_event_id, created_at
FROM core.tasks t
WHERE t.assignee_id = $1::uuid
    AND t.due_on = $2::date
    AND ($3::text = 'all' OR t.status = $3::text)
    AND (t.due_on, t.id) > ($4::date, $5::uuid)
ORDER BY t.due_on, t.id
LIMIT $6
`

type ListTasksForDayParams struct {
	AssigneeID uuid.UUID
	DueOn      time.Time
	Status     string
	AfterDueOn time.Time
	AfterID    uuid.UUID
	RowLimit   int32
}

func (q *Queries) ListTasksForDay(ctx context.Context, arg ListTasksForDayParams) ([]CoreTask, error) {
	rows, err := q.db.Query(ctx, listTasksForDay,
		arg.AssigneeID,
		arg.DueOn,
		arg.Status,
		arg.AfterDueOn,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreTask
	for rows.Next() {
		var i CoreTask
		if err := rows.Scan(
			&i.ID,
			&i.AssigneeID,
			&i.ContactID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.DueOn,
			&i.OriginSource,
			&i.OriginEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptionsForEvent = `-- name: ListWebhookSubscriptionsForEvent :many
SELECT id, user_id, url, events, secret, created_at
FROM core.webhook_subscriptions
WHERE $1::text = ANY (events)
ORDER BY id
`

func (q *Queries) ListWebhookSubscriptionsForEvent(ctx context.Context, dollar_1 string) ([]CoreWebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptionsForEvent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreWebhookSubscription
	for rows.Next() {
		var i CoreWebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Events,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptionsForUser = `-- name: ListWebhookSubscriptionsForUser :many
SELECT id, user_id, url, events, secret, created_at
FROM core.webhook_subscriptions
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListWebhookSubscriptionsForUser(ctx context.Context, userID uuid.UUID) ([]CoreWebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreWebhookSubscription
	for rows.Next() {
		var i CoreWebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Events,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
DELETE FROM core.api_tokens
WHERE id = $1 AND user_id = $2
`

type RevokeAPITokenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleWebhookDelivery = `-- name: SettleWebhookDelivery :exec
UPDATE core.webhook_deliveries
SET status = $2, deliver_after = $3, last_error = $4
WHERE id = $1
`

type SettleWebhookDeliveryParams struct {
	ID           uuid.UUID
	Status       string
	DeliverAfter time.Time
	LastError    pgtype.Text
}

func (q *Queries) SettleWebhookDelivery(ctx context.Context, arg SettleWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, settleWebhookDelivery,
		arg.ID,
		arg.Status,
		arg.DeliverAfter,
		arg.LastError,
	)
	return err
}

const tenantForUser = `-- name: TenantForUser :one
SELECT t.id, t.name
FROM core.tenants t
LEFT JOIN core.tenant_members m ON m.tenant_id = t.id AND m.user_id = $1::uuid
WHERE m.user_id IS NOT NULL OR t.id = $2::uuid
ORDER BY m.user_id IS NOT NULL DESC
LIMIT 1
`

type TenantForUserParams struct {
	UserID    uuid.UUID
	DefaultID uuid.UUID
}

type TenantForUserRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) TenantForUser(ctx context.Context, arg TenantForUserParams) (TenantForUserRow, error) {
	row := q.db.QueryRow(ctx, tenantForUser, arg.UserID, arg.DefaultID)
	var i TenantForUserRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE core.api_tokens
SET last_used_at = $2
WHERE id = $1
`

type TouchAPITokenParams struct {
	ID         uuid.UUID
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.Exec(ctx, touchAPIToken, arg.ID, arg.LastUsedAt)
	return err
}

const updateContactName = `-- name: UpdateContactName :one
UPDATE core.contacts SET name = $2 WHERE id = $1
RETURNING id, name, created_at
`

type UpdateContactNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateContactName(ctx context.Context, arg UpdateContactNameParams) (CoreContact, error) {
	row := q.db.QueryRow(ctx, updateContactName, arg.ID, arg.Name)
	var i CoreContact
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE core.tasks
SET title = $2, status = $3, priority = $4, due_on = $5
WHERE id = $1
RETURNING id, assignee_id, contact_id, title, status, priority, due_on,
    origin_source, origin_event_id, created_at
`

type UpdateTaskParams struct {
	ID       uuid.UUID
	Title    string
	Status   string
	Priority int16
	DueOn    time.Time
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (CoreTask, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.DueOn,
	)
	var i CoreTask
	err := row.Scan(
		&i.ID,
		&i.AssigneeID,
		&i.ContactID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.DueOn,
		&i.OriginSource,
		&i.OriginEventID,
		&i.CreatedAt,
	)
	return i, err
}
