coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: 100%

ignore:
  - "internal/postgres/db"
  - "internal/testdb"
  - "internal/graphroot"
  - "graph/generated.go"
  - "graph/model"
