coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 100%

ignore:
  - internal/postgres/db
  - internal/testdb
  - cmd/alphone/main.go
  - cmd/pluginwire/main.go
