type Contact {
  id: UUID!
  name: String!
  createdAt: DateTime! @goField(forceResolver: true)
  identities: [ContactIdentity!]! @goField(forceResolver: true)
  tasks(status: String, first: Int, after: String): TaskConnection! @goField(forceResolver: true)
}

type ContactIdentity {
  id: UUID!
  channel: String!
  identifier: String!
  displayName: String!
}

type ContactEdge {
  node: Contact!
  cursor: String!
}

type ContactConnection {
  edges: [ContactEdge!]!
  pageInfo: PageInfo!
}

extend type Query {
  contacts(q: String, first: Int, after: String): ContactConnection!
  contact(id: UUID!): Contact
}

input ContactIdentityInput {
  channel: String!
  identifier: String!
  displayName: String
}

type Mutation {
  createContact(name: String!, identities: [ContactIdentityInput!]): Contact!
  renameContact(id: UUID!, name: String!): Contact!
  addContactIdentity(contactId: UUID!, identity: ContactIdentityInput!): ContactIdentity!
  deleteContactIdentity(contactId: UUID!, identityId: UUID!): Boolean!
}
