directive @goField(
  forceResolver: Boolean
  name: String
  omittable: Boolean
) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @scope(area: String!, write: Boolean!) on FIELD_DEFINITION

scalar UUID
scalar DateTime
scalar Date
scalar Upload
scalar JSON

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Tenant {
  id: UUID!
  name: String!
}

type Query {
  version: String! @scope(area: "meta", write: false)
  tenant: Tenant! @scope(area: "meta", write: false)
}

type Subscription {
  coreEvent: String! @scope(area: "events", write: false)
}
