// SPDX-License-Identifier: Elastic-2.0

// Code generated by pluginwire. DO NOT EDIT.

package graphroot

import (
	"errors"
	graph "github.com/gopherium/alphone/graph"
	graphres "github.com/gopherium/alphone/internal/graphres"
	fields "github.com/gopherium/alphone/plugins/fields"
	importer "github.com/gopherium/alphone/plugins/importer"
	whatsapp "github.com/gopherium/alphone/plugins/whatsapp"
	sdk "github.com/gopherium/alphone/sdk"
)

// CoreGraphResolvers lists the resolver sets the core contributes to the graph.
type CoreGraphResolvers interface {
	ContactResolvers() graphres.ContactResolvers
	MutationResolvers() graphres.MutationResolvers
	QueryResolvers() graphres.QueryResolvers
	SubscriptionResolvers() graphres.SubscriptionResolvers
	TaskResolvers() graphres.TaskResolvers
}

// FieldsGraphResolvers lists the resolver sets the fields plugin contributes to the graph.
type FieldsGraphResolvers interface {
	MutationResolvers() fields.MutationResolvers
	QueryResolvers() fields.QueryResolvers
}

// ImporterGraphResolvers lists the resolver sets the importer plugin contributes to the graph.
type ImporterGraphResolvers interface {
	ImportJobResolvers() importer.ImportJobResolvers
	MutationResolvers() importer.MutationResolvers
	QueryResolvers() importer.QueryResolvers
}

// WhatsappGraphResolvers lists the resolver sets the whatsapp plugin contributes to the graph.
type WhatsappGraphResolvers interface {
	ContactResolvers() whatsapp.ContactResolvers
	MutationResolvers() whatsapp.MutationResolvers
	QueryResolvers() whatsapp.QueryResolvers
	SubscriptionResolvers() whatsapp.SubscriptionResolvers
	WhatsAppConversationResolvers() whatsapp.WhatsAppConversationResolvers
}

// coreContactResolvers names the core Contact resolver set for embedding.
type coreContactResolvers = graphres.ContactResolvers

// whatsappContactResolvers names the whatsapp Contact resolver set for embedding.
type whatsappContactResolvers = whatsapp.ContactResolvers

// composedContactResolver merges every contributed Contact resolver set.
type composedContactResolver struct {
	coreContactResolvers
	whatsappContactResolvers
}

// coreMutationResolvers names the core Mutation resolver set for embedding.
type coreMutationResolvers = graphres.MutationResolvers

// fieldsMutationResolvers names the fields Mutation resolver set for embedding.
type fieldsMutationResolvers = fields.MutationResolvers

// importerMutationResolvers names the importer Mutation resolver set for embedding.
type importerMutationResolvers = importer.MutationResolvers

// whatsappMutationResolvers names the whatsapp Mutation resolver set for embedding.
type whatsappMutationResolvers = whatsapp.MutationResolvers

// composedMutationResolver merges every contributed Mutation resolver set.
type composedMutationResolver struct {
	coreMutationResolvers
	fieldsMutationResolvers
	importerMutationResolvers
	whatsappMutationResolvers
}

// coreQueryResolvers names the core Query resolver set for embedding.
type coreQueryResolvers = graphres.QueryResolvers

// fieldsQueryResolvers names the fields Query resolver set for embedding.
type fieldsQueryResolvers = fields.QueryResolvers

// importerQueryResolvers names the importer Query resolver set for embedding.
type importerQueryResolvers = importer.QueryResolvers

// whatsappQueryResolvers names the whatsapp Query resolver set for embedding.
type whatsappQueryResolvers = whatsapp.QueryResolvers

// composedQueryResolver merges every contributed Query resolver set.
type composedQueryResolver struct {
	coreQueryResolvers
	fieldsQueryResolvers
	importerQueryResolvers
	whatsappQueryResolvers
}

// coreSubscriptionResolvers names the core Subscription resolver set for embedding.
type coreSubscriptionResolvers = graphres.SubscriptionResolvers

// whatsappSubscriptionResolvers names the whatsapp Subscription resolver set for embedding.
type whatsappSubscriptionResolvers = whatsapp.SubscriptionResolvers

// composedSubscriptionResolver merges every contributed Subscription resolver set.
type composedSubscriptionResolver struct {
	coreSubscriptionResolvers
	whatsappSubscriptionResolvers
}

// graphRoot composes the core and plugin resolver sets into the resolver root.
type graphRoot struct {
	core     CoreGraphResolvers
	fields   FieldsGraphResolvers
	importer ImporterGraphResolvers
	whatsapp WhatsappGraphResolvers
}

// NewGraphRoot composes the core resolver sets with every graphql plugin's.
func NewGraphRoot(
	core CoreGraphResolvers,
	fieldsPlugin FieldsGraphResolvers,
	importerPlugin ImporterGraphResolvers,
	whatsappPlugin WhatsappGraphResolvers,
) graph.ResolverRoot {
	return graphRoot{core: core, fields: fieldsPlugin, importer: importerPlugin, whatsapp: whatsappPlugin}
}

// FromPlugins finds each graphql plugin among the registered plugins and composes the resolver root.
func FromPlugins(core CoreGraphResolvers, plugins []sdk.Plugin) (graph.ResolverRoot, error) {
	var fieldsPlugin FieldsGraphResolvers
	var importerPlugin ImporterGraphResolvers
	var whatsappPlugin WhatsappGraphResolvers
	for _, plugin := range plugins {
		if candidate, ok := plugin.(FieldsGraphResolvers); ok {
			fieldsPlugin = candidate
		}
		if candidate, ok := plugin.(ImporterGraphResolvers); ok {
			importerPlugin = candidate
		}
		if candidate, ok := plugin.(WhatsappGraphResolvers); ok {
			whatsappPlugin = candidate
		}
	}
	if fieldsPlugin == nil {
		return nil, errors.New("graphroot: no registered plugin provides the fields resolver sets")
	}
	if importerPlugin == nil {
		return nil, errors.New("graphroot: no registered plugin provides the importer resolver sets")
	}
	if whatsappPlugin == nil {
		return nil, errors.New("graphroot: no registered plugin provides the whatsapp resolver sets")
	}
	return NewGraphRoot(core, fieldsPlugin, importerPlugin, whatsappPlugin), nil
}

// Contact returns the Contact resolver set.
func (g graphRoot) Contact() graph.ContactResolver {
	return composedContactResolver{
		g.core.ContactResolvers(),
		g.whatsapp.ContactResolvers(),
	}
}

// ImportJob returns the ImportJob resolver set.
func (g graphRoot) ImportJob() graph.ImportJobResolver {
	return g.importer.ImportJobResolvers()
}

// Mutation returns the Mutation resolver set.
func (g graphRoot) Mutation() graph.MutationResolver {
	return composedMutationResolver{
		g.core.MutationResolvers(),
		g.fields.MutationResolvers(),
		g.importer.MutationResolvers(),
		g.whatsapp.MutationResolvers(),
	}
}

// Query returns the Query resolver set.
func (g graphRoot) Query() graph.QueryResolver {
	return composedQueryResolver{
		g.core.QueryResolvers(),
		g.fields.QueryResolvers(),
		g.importer.QueryResolvers(),
		g.whatsapp.QueryResolvers(),
	}
}

// Subscription returns the Subscription resolver set.
func (g graphRoot) Subscription() graph.SubscriptionResolver {
	return composedSubscriptionResolver{
		g.core.SubscriptionResolvers(),
		g.whatsapp.SubscriptionResolvers(),
	}
}

// Task returns the Task resolver set.
func (g graphRoot) Task() graph.TaskResolver {
	return g.core.TaskResolvers()
}

// WhatsAppConversation returns the WhatsAppConversation resolver set.
func (g graphRoot) WhatsAppConversation() graph.WhatsAppConversationResolver {
	return g.whatsapp.WhatsAppConversationResolvers()
}
