// SPDX-License-Identifier: Elastic-2.0

// Code generated by pluginwire. DO NOT EDIT.

package graphroot

import (
	graph "github.com/gopherium/alphone/graph"
	sdk "github.com/gopherium/alphone/sdk"
)

// NewGraphRoot returns the core resolver root, no plugin extends the graph.
func NewGraphRoot(core graph.ResolverRoot) graph.ResolverRoot {
	return core
}

// FromPlugins composes the resolver root, no registered plugin extends the graph.
func FromPlugins(core graph.ResolverRoot, _ []sdk.Plugin) (graph.ResolverRoot, error) {
	return core, nil
}
