// SPDX-License-Identifier: Elastic-2.0

// Code generated by pluginwire. DO NOT EDIT.

package graphroot

import (
	"errors"
	"fmt"

	fields "github.com/gopherium/alphone/plugins/fields"
	importer "github.com/gopherium/alphone/plugins/importer"
	whatsapp "github.com/gopherium/alphone/plugins/whatsapp"

	sdk "github.com/gopherium/alphone/sdk"
)

// All registers every plugin, answering the ones that registered and an error naming each failure.
func All(deps sdk.Deps) ([]sdk.Plugin, error) {
	plugins := make([]sdk.Plugin, 0, 3)
	var failed []error
	fieldsPlugin, err := fields.Register(deps)
	if err != nil {
		failed = append(failed, fmt.Errorf("plugin fields: %w", err))
	} else {
		plugins = append(plugins, fieldsPlugin)
	}
	importerPlugin, err := importer.Register(deps)
	if err != nil {
		failed = append(failed, fmt.Errorf("plugin importer: %w", err))
	} else {
		plugins = append(plugins, importerPlugin)
	}
	whatsappPlugin, err := whatsapp.Register(deps)
	if err != nil {
		failed = append(failed, fmt.Errorf("plugin whatsapp: %w", err))
	} else {
		plugins = append(plugins, whatsappPlugin)
	}
	return plugins, errors.Join(failed...)
}
