// SPDX-License-Identifier: Elastic-2.0

// Code generated by pluginwire. DO NOT EDIT.

package graphroot

import (
	fields "github.com/gopherium/alphone/plugins/fields"
	importer "github.com/gopherium/alphone/plugins/importer"
	whatsapp "github.com/gopherium/alphone/plugins/whatsapp"

	"github.com/gopherium/alphone/sdk"
)

// All registers every plugin and returns them in registration order.
func All(deps sdk.Deps) ([]sdk.Plugin, error) {
	plugins := make([]sdk.Plugin, 0, 3)
	fieldsPlugin, err := fields.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, fieldsPlugin)
	importerPlugin, err := importer.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, importerPlugin)
	whatsappPlugin, err := whatsapp.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, whatsappPlugin)
	return plugins, nil
}
