// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"os"
	"path/filepath"
	"testing"
)

const whatsappManifest = `{
	"id": "whatsapp",
	"name": "WhatsApp",
	"backend": "github.com/gopherium/alphone/plugins/whatsapp",
	"frontend": "@alphone/plugin-whatsapp"
}`

func writePlugin(t *testing.T, root, dir, manifestJSON string) {
	t.Helper()
	pluginDir := filepath.Join(root, "plugins", dir)
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		t.Fatalf("creating %s: %v", pluginDir, err)
	}
	if manifestJSON == "" {
		return
	}
	if err := os.WriteFile(filepath.Join(pluginDir, "plugin.json"), []byte(manifestJSON), 0o644); err != nil {
		t.Fatalf("writing manifest: %v", err)
	}
}

func TestLoadManifestsReadsValidPlugins(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "sms-relay", `{"id": "sms-relay", "name": "SMS Relay", "backend": "example.com/sms"}`)
	writePlugin(t, root, "whatsapp", whatsappManifest)
	if err := os.WriteFile(filepath.Join(root, "plugins", "README.md"), []byte("not a plugin"), 0o644); err != nil {
		t.Fatalf("writing stray file: %v", err)
	}

	manifests, err := loadManifests(filepath.Join(root, "plugins"))

	if err != nil {
		t.Fatalf("loadManifests() error = %v, want nil", err)
	}
	if len(manifests) != 2 {
		t.Fatalf("manifests = %d, want 2", len(manifests))
	}
	if manifests[0].ID != "sms-relay" || manifests[1].ID != "whatsapp" {
		t.Errorf("order = [%q, %q], want directory order [%q, %q]",
			manifests[0].ID, manifests[1].ID, "sms-relay", "whatsapp")
	}
	if manifests[1].Backend != "github.com/gopherium/alphone/plugins/whatsapp" {
		t.Errorf("backend = %q, want the module import path", manifests[1].Backend)
	}
	if manifests[1].Frontend != "@alphone/plugin-whatsapp" {
		t.Errorf("frontend = %q, want the npm package name", manifests[1].Frontend)
	}
}

func TestLoadManifestsRejectsInvalidPlugins(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		dir      string
		manifest string
	}{
		"missing manifest":             {dir: "ghost", manifest: ""},
		"malformed json":               {dir: "broken", manifest: `{`},
		"missing id":                   {dir: "anon", manifest: `{"name": "Anon", "backend": "example.com/anon"}`},
		"uppercase id":                 {dir: "Loud", manifest: `{"id": "Loud", "name": "Loud", "backend": "example.com/loud"}`},
		"id and directory disagree":    {dir: "alias", manifest: `{"id": "other", "name": "Alias", "backend": "example.com/alias"}`},
		"missing name":                 {dir: "nameless", manifest: `{"id": "nameless", "backend": "example.com/nameless"}`},
		"neither backend nor frontend": {dir: "hollow", manifest: `{"id": "hollow", "name": "Hollow"}`},
	}

	for testName, tc := range tests {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			writePlugin(t, root, tc.dir, tc.manifest)

			if _, err := loadManifests(filepath.Join(root, "plugins")); err == nil {
				t.Fatal("loadManifests() error = nil, want a validation error")
			}
		})
	}
}

func TestGenerateGoWiresBackendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateGo([]manifest{
		{ID: "sms-relay", Name: "SMS Relay", Backend: "example.com/sms"},
		{ID: "whatsapp", Name: "WhatsApp", Backend: "github.com/gopherium/alphone/plugins/whatsapp", Frontend: "@alphone/plugin-whatsapp"},
	}))

	want := `// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	sms_relay "example.com/sms"
	whatsapp "github.com/gopherium/alphone/plugins/whatsapp"

	"github.com/gopherium/alphone/sdk"
)

func registerPlugins(deps sdk.Deps) ([]sdk.Plugin, error) {
	plugins := make([]sdk.Plugin, 0, 2)
	sms_relayPlugin, err := sms_relay.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, sms_relayPlugin)
	whatsappPlugin, err := whatsapp.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, whatsappPlugin)
	return plugins, nil
}
`
	if got != want {
		t.Errorf("generateGo() = %q, want %q", got, want)
	}
}

func TestGenerateGoWithoutBackendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateGo([]manifest{
		{ID: "pretty", Name: "Pretty", Frontend: "@alphone/plugin-pretty"},
	}))

	want := `// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	"github.com/gopherium/alphone/sdk"
)

func registerPlugins(_ sdk.Deps) ([]sdk.Plugin, error) {
	return []sdk.Plugin{}, nil
}
`
	if got != want {
		t.Errorf("generateGo() = %q, want %q", got, want)
	}
}

func TestGenerateTSWiresFrontendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateTS([]manifest{
		{ID: "sms-relay", Name: "SMS Relay", Backend: "example.com/sms", Frontend: "@alphone/plugin-sms-relay"},
		{ID: "whatsapp", Name: "WhatsApp", Frontend: "@alphone/plugin-whatsapp"},
	}))

	want := `// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by pluginwire. DO NOT EDIT.

import type { FrontendPlugin } from '@alphone/frontend-sdk'
import { plugin as sms_relay } from '@alphone/plugin-sms-relay'
import { plugin as whatsapp } from '@alphone/plugin-whatsapp'

export const plugins: FrontendPlugin[] = [sms_relay, whatsapp]
`
	if got != want {
		t.Errorf("generateTS() = %q, want %q", got, want)
	}
}

func TestGenerateTSWithoutFrontendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateTS([]manifest{
		{ID: "headless", Name: "Headless", Backend: "example.com/headless"},
	}))

	want := `// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by pluginwire. DO NOT EDIT.

import type { FrontendPlugin } from '@alphone/frontend-sdk'

export const plugins: FrontendPlugin[] = []
`
	if got != want {
		t.Errorf("generateTS() = %q, want %q", got, want)
	}
}

func TestRunWritesWiringFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "whatsapp", whatsappManifest)
	for _, dir := range []string{"cmd/alphone", "frontend/src/plugins"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatalf("creating %s: %v", dir, err)
		}
	}

	if err := run(root); err != nil {
		t.Fatalf("run() error = %v, want nil", err)
	}

	goSrc, err := os.ReadFile(filepath.Join(root, "cmd", "alphone", "plugins_gen.go"))
	if err != nil {
		t.Fatalf("reading generated Go wiring: %v", err)
	}
	tsSrc, err := os.ReadFile(filepath.Join(root, "frontend", "src", "plugins", "index.ts"))
	if err != nil {
		t.Fatalf("reading generated TS wiring: %v", err)
	}
	manifests, err := loadManifests(filepath.Join(root, "plugins"))
	if err != nil {
		t.Fatalf("loadManifests() error = %v, want nil", err)
	}
	if string(goSrc) != string(generateGo(manifests)) {
		t.Errorf("plugins_gen.go = %q, want the generated wiring", goSrc)
	}
	if string(tsSrc) != string(generateTS(manifests)) {
		t.Errorf("index.ts = %q, want the generated registry", tsSrc)
	}
}

func TestRunReportsFailures(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		prepare func(t *testing.T, root string)
	}{
		"missing plugins directory": {
			prepare: func(_ *testing.T, _ string) {},
		},
		"unwritable go wiring": {
			prepare: func(t *testing.T, root string) {
				writePlugin(t, root, "whatsapp", whatsappManifest)
			},
		},
		"unwritable ts wiring": {
			prepare: func(t *testing.T, root string) {
				writePlugin(t, root, "whatsapp", whatsappManifest)
				if err := os.MkdirAll(filepath.Join(root, "cmd", "alphone"), 0o755); err != nil {
					t.Fatalf("creating cmd/alphone: %v", err)
				}
			},
		},
	}

	for testName, tc := range tests {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			tc.prepare(t, root)

			if err := run(root); err == nil {
				t.Fatal("run() error = nil, want an error")
			}
		})
	}
}

func TestRepositoryWiringIsUpToDate(t *testing.T) {
	t.Parallel()

	manifests, err := loadManifests(filepath.Join("..", "..", "plugins"))
	if err != nil {
		t.Fatalf("loadManifests() error = %v, want nil", err)
	}

	goSrc, err := os.ReadFile(filepath.Join("..", "..", "cmd", "alphone", "plugins_gen.go"))
	if err != nil {
		t.Fatalf("reading committed Go wiring: %v", err)
	}
	tsSrc, err := os.ReadFile(filepath.Join("..", "..", "frontend", "src", "plugins", "index.ts"))
	if err != nil {
		t.Fatalf("reading committed TS wiring: %v", err)
	}

	if string(goSrc) != string(generateGo(manifests)) {
		t.Error("cmd/alphone/plugins_gen.go is stale; run make generate")
	}
	if string(tsSrc) != string(generateTS(manifests)) {
		t.Error("frontend/src/plugins/index.ts is stale; run make generate")
	}
}
