// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type manifest struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Backend  string `json:"backend"`
	Frontend string `json:"frontend"`
}

var idPattern = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)

func loadManifests(dir string) ([]manifest, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("pluginwire: reading plugins directory: %w", err)
	}
	manifests := make([]manifest, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		path := filepath.Join(dir, entry.Name(), "plugin.json")
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("pluginwire: %s: %w", path, err)
		}
		var m manifest
		if err := json.Unmarshal(data, &m); err != nil {
			return nil, fmt.Errorf("pluginwire: %s: %w", path, err)
		}
		if err := validate(m, entry.Name()); err != nil {
			return nil, fmt.Errorf("pluginwire: %s: %w", path, err)
		}
		manifests = append(manifests, m)
	}
	return manifests, nil
}

func validate(m manifest, dir string) error {
	if !idPattern.MatchString(m.ID) {
		return fmt.Errorf("id %q must match %s", m.ID, idPattern)
	}
	if m.ID != dir {
		return fmt.Errorf("id %q does not match directory %q", m.ID, dir)
	}
	if m.Name == "" {
		return errors.New("name is required")
	}
	if m.Backend == "" && m.Frontend == "" {
		return errors.New("at least one of backend or frontend is required")
	}
	return nil
}

func goName(id string) string {
	return strings.ReplaceAll(id, "-", "_")
}

const generatedHeader = "// SPDX-License-Identifier: AGPL-3.0-or-later\n\n// Code generated by pluginwire. DO NOT EDIT.\n\n"

func generateGo(manifests []manifest) []byte {
	backends := make([]manifest, 0, len(manifests))
	for _, m := range manifests {
		if m.Backend != "" {
			backends = append(backends, m)
		}
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("package main\n\nimport (\n")
	for _, m := range backends {
		fmt.Fprintf(&b, "\t%s %q\n", goName(m.ID), m.Backend)
	}
	if len(backends) > 0 {
		b.WriteString("\n")
	}
	b.WriteString("\t\"github.com/gopherium/alphone/sdk\"\n)\n\n")
	if len(backends) == 0 {
		b.WriteString("func registerPlugins(_ sdk.Deps) ([]sdk.Plugin, error) {\n\treturn []sdk.Plugin{}, nil\n}\n")
		return []byte(b.String())
	}
	fmt.Fprintf(&b, "func registerPlugins(deps sdk.Deps) ([]sdk.Plugin, error) {\n\tplugins := make([]sdk.Plugin, 0, %d)\n", len(backends))
	for _, m := range backends {
		name := goName(m.ID)
		fmt.Fprintf(&b, "\t%sPlugin, err := %s.Register(deps)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tplugins = append(plugins, %sPlugin)\n", name, name, name)
	}
	b.WriteString("\treturn plugins, nil\n}\n")
	return []byte(b.String())
}

func generateTS(manifests []manifest) []byte {
	frontends := make([]manifest, 0, len(manifests))
	for _, m := range manifests {
		if m.Frontend != "" {
			frontends = append(frontends, m)
		}
	}

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("import type { FrontendPlugin } from '@alphone/frontend-sdk'\n")
	names := make([]string, 0, len(frontends))
	for _, m := range frontends {
		name := goName(m.ID)
		names = append(names, name)
		fmt.Fprintf(&b, "import { plugin as %s } from '%s'\n", name, m.Frontend)
	}
	fmt.Fprintf(&b, "\nexport const plugins: FrontendPlugin[] = [%s]\n", strings.Join(names, ", "))
	return []byte(b.String())
}

func run(root string) error {
	manifests, err := loadManifests(filepath.Join(root, "plugins"))
	if err != nil {
		return err
	}
	goPath := filepath.Join(root, "cmd", "alphone", "plugins_gen.go")
	if err := os.WriteFile(goPath, generateGo(manifests), 0o644); err != nil {
		return fmt.Errorf("pluginwire: %w", err)
	}
	tsPath := filepath.Join(root, "frontend", "src", "plugins", "index.ts")
	if err := os.WriteFile(tsPath, generateTS(manifests), 0o644); err != nil {
		return fmt.Errorf("pluginwire: %w", err)
	}
	return nil
}
