// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Contact struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	CreatedAt  time.Time          `json:"createdAt"`
	Identities []*ContactIdentity `json:"identities"`
	Tasks      *TaskConnection    `json:"tasks"`
}

type ContactConnection struct {
	Edges    []*ContactEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ContactEdge struct {
	Node   *Contact `json:"node"`
	Cursor string   `json:"cursor"`
}

type ContactIdentity struct {
	ID          uuid.UUID `json:"id"`
	Channel     string    `json:"channel"`
	Identifier  string    `json:"identifier"`
	DisplayName string    `json:"displayName"`
}

type ContactIdentityInput struct {
	Channel     string  `json:"channel"`
	Identifier  string  `json:"identifier"`
	DisplayName *string `json:"displayName,omitempty"`
}

type CreateTaskInput struct {
	Title         string     `json:"title"`
	DueOn         time.Time  `json:"dueOn"`
	Priority      *int       `json:"priority,omitempty"`
	ContactID     *uuid.UUID `json:"contactId,omitempty"`
	OriginEventID *uuid.UUID `json:"originEventId,omitempty"`
}

type CreateTaskPayload struct {
	Task   *Task `json:"task"`
	Replay bool  `json:"replay"`
}

type CreateWebhookPayload struct {
	Webhook *Webhook `json:"webhook"`
	Secret  string   `json:"secret"`
}

type Identity struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Name  string    `json:"name"`
}

type LoginPayload struct {
	Me *Identity `json:"me"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Task struct {
	ID            uuid.UUID  `json:"id"`
	AssigneeID    uuid.UUID  `json:"assigneeId"`
	ContactID     *uuid.UUID `json:"contactId,omitempty"`
	Title         string     `json:"title"`
	Status        string     `json:"status"`
	Priority      int        `json:"priority"`
	DueOn         time.Time  `json:"dueOn"`
	OriginSource  *string    `json:"originSource,omitempty"`
	OriginEventID *uuid.UUID `json:"originEventId,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
	Contact       *Contact   `json:"contact,omitempty"`
}

type TaskConnection struct {
	Edges    []*TaskEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type TaskEdge struct {
	Node   *Task  `json:"node"`
	Cursor string `json:"cursor"`
}

type UpdateTaskInput struct {
	Title    *string    `json:"title,omitempty"`
	DueOn    *time.Time `json:"dueOn,omitempty"`
	Status   *string    `json:"status,omitempty"`
	Priority *int       `json:"priority,omitempty"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Disabled  bool      `json:"disabled"`
	CreatedAt time.Time `json:"createdAt"`
}

type Webhook struct {
	ID        uuid.UUID `json:"id"`
	URL       string    `json:"url"`
	Events    []string  `json:"events"`
	CreatedAt time.Time `json:"createdAt"`
}
