// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type APIToken struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	CreatedAt  time.Time  `json:"createdAt"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	ExpiresAt  *time.Time `json:"expiresAt,omitempty"`
}

type APITokenSecret struct {
	Token  *APIToken `json:"token"`
	Secret string    `json:"secret"`
}

type Contact struct {
	ID                    uuid.UUID               `json:"id"`
	Name                  string                  `json:"name"`
	CreatedAt             time.Time               `json:"createdAt"`
	Identities            []*ContactIdentity      `json:"identities"`
	Tasks                 *TaskConnection         `json:"tasks"`
	Field                 any                     `json:"field,omitempty"`
	WhatsAppConversations []*WhatsAppConversation `json:"whatsAppConversations"`
}

type ContactConnection struct {
	Edges    []*ContactEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ContactEdge struct {
	Node   *Contact `json:"node"`
	Cursor string   `json:"cursor"`
}

type ContactIdentity struct {
	ID          uuid.UUID `json:"id"`
	Channel     string    `json:"channel"`
	Identifier  string    `json:"identifier"`
	DisplayName string    `json:"displayName"`
}

type ContactIdentityInput struct {
	Channel     string  `json:"channel"`
	Identifier  string  `json:"identifier"`
	DisplayName *string `json:"displayName,omitempty"`
}

type CreateTaskInput struct {
	Title         string     `json:"title"`
	DueOn         time.Time  `json:"dueOn"`
	Priority      *int       `json:"priority,omitempty"`
	ContactID     *uuid.UUID `json:"contactId,omitempty"`
	OriginEventID *uuid.UUID `json:"originEventId,omitempty"`
}

type CreateTaskPayload struct {
	Task   *Task `json:"task"`
	Replay bool  `json:"replay"`
}

type CreateWebhookPayload struct {
	Webhook *Webhook `json:"webhook"`
	Secret  string   `json:"secret"`
}

type FieldDefinition struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Label      string     `json:"label"`
	Kind       FieldKind  `json:"kind"`
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`
}

type Identity struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	Role         string    `json:"role"`
	Capabilities []string  `json:"capabilities"`
	Grantable    []string  `json:"grantable"`
}

type ImportAssignment struct {
	Column int    `json:"column"`
	Field  string `json:"field"`
}

type ImportAssignmentInput struct {
	Column int    `json:"column"`
	Field  string `json:"field"`
}

type ImportCommitPayload struct {
	ID       uuid.UUID `json:"id"`
	Imported int       `json:"imported"`
	Skipped  int       `json:"skipped"`
	Failed   int       `json:"failed"`
}

type ImportContact struct {
	ContactID uuid.UUID `json:"contactId"`
	Name      string    `json:"name"`
	RowID     uuid.UUID `json:"rowId"`
}

type ImportField struct {
	Name     string `json:"name"`
	Label    string `json:"label"`
	Required bool   `json:"required"`
}

type ImportJob struct {
	ID            uuid.UUID           `json:"id"`
	UserID        uuid.UUID           `json:"userId"`
	Filename      string              `json:"filename"`
	State         string              `json:"state"`
	RowCount      int                 `json:"rowCount"`
	ImportedCount int                 `json:"importedCount"`
	SkippedCount  int                 `json:"skippedCount"`
	FailedCount   int                 `json:"failedCount"`
	CreatedAt     time.Time           `json:"createdAt"`
	Columns       []string            `json:"columns"`
	Mapping       []*ImportAssignment `json:"mapping"`
	Rows          []*ImportRow        `json:"rows"`
	Contacts      []*ImportContact    `json:"contacts"`
}

type ImportRow struct {
	ID        uuid.UUID  `json:"id"`
	Position  int        `json:"position"`
	Cells     []string   `json:"cells"`
	Outcome   string     `json:"outcome"`
	Reason    *string    `json:"reason,omitempty"`
	ContactID *uuid.UUID `json:"contactId,omitempty"`
}

type LoginPayload struct {
	Me *Identity `json:"me"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type Task struct {
	ID            uuid.UUID  `json:"id"`
	AssigneeID    uuid.UUID  `json:"assigneeId"`
	ContactID     *uuid.UUID `json:"contactId,omitempty"`
	Title         string     `json:"title"`
	Status        string     `json:"status"`
	Priority      int        `json:"priority"`
	DueOn         time.Time  `json:"dueOn"`
	OriginSource  *string    `json:"originSource,omitempty"`
	OriginEventID *uuid.UUID `json:"originEventId,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
	Contact       *Contact   `json:"contact,omitempty"`
}

type TaskConnection struct {
	Edges    []*TaskEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type TaskEdge struct {
	Node   *Task  `json:"node"`
	Cursor string `json:"cursor"`
}

type Tenant struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type UpdateTaskInput struct {
	Title    *string    `json:"title,omitempty"`
	DueOn    *time.Time `json:"dueOn,omitempty"`
	Status   *string    `json:"status,omitempty"`
	Priority *int       `json:"priority,omitempty"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Disabled  bool      `json:"disabled"`
	CreatedAt time.Time `json:"createdAt"`
	Role      string    `json:"role"`
}

type Webhook struct {
	ID        uuid.UUID `json:"id"`
	URL       string    `json:"url"`
	Events    []string  `json:"events"`
	CreatedAt time.Time `json:"createdAt"`
}

type WhatsAppConversation struct {
	ID                 uuid.UUID          `json:"id"`
	ExternalID         string             `json:"externalId"`
	Status             string             `json:"status"`
	LastActivityAt     time.Time          `json:"lastActivityAt"`
	LastMessagePreview *string            `json:"lastMessagePreview,omitempty"`
	Contact            *Contact           `json:"contact"`
	Messages           []*WhatsAppMessage `json:"messages"`
}

type WhatsAppMedia struct {
	Status       string  `json:"status"`
	MimeType     string  `json:"mimeType"`
	Filename     *string `json:"filename,omitempty"`
	FileSize     *int    `json:"fileSize,omitempty"`
	Voice        bool    `json:"voice"`
	Animated     bool    `json:"animated"`
	DownloadPath string  `json:"downloadPath"`
}

type WhatsAppMessage struct {
	ID           uuid.UUID      `json:"id"`
	ExternalID   string         `json:"externalId"`
	Direction    string         `json:"direction"`
	Content      string         `json:"content"`
	ContentType  string         `json:"contentType"`
	SentAt       time.Time      `json:"sentAt"`
	Status       *string        `json:"status,omitempty"`
	StatusDetail *string        `json:"statusDetail,omitempty"`
	Media        *WhatsAppMedia `json:"media,omitempty"`
}

type FieldKind string

const (
	FieldKindText     FieldKind = "TEXT"
	FieldKindLongtext FieldKind = "LONGTEXT"
	FieldKindNumber   FieldKind = "NUMBER"
	FieldKindBoolean  FieldKind = "BOOLEAN"
	FieldKindDate     FieldKind = "DATE"
	FieldKindSelect   FieldKind = "SELECT"
)

var AllFieldKind = []FieldKind{
	FieldKindText,
	FieldKindLongtext,
	FieldKindNumber,
	FieldKindBoolean,
	FieldKindDate,
	FieldKindSelect,
}

func (e FieldKind) IsValid() bool {
	switch e {
	case FieldKindText, FieldKindLongtext, FieldKindNumber, FieldKindBoolean, FieldKindDate, FieldKindSelect:
		return true
	}
	return false
}

func (e FieldKind) String() string {
	return string(e)
}

func (e *FieldKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FieldKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FieldKind", str)
	}
	return nil
}

func (e FieldKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FieldKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FieldKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
