// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by pluginwire. DO NOT EDIT.

import type { FrontendPlugin } from '@alphone/frontend-sdk'
import { plugin as whatsapp } from '@alphone/plugin-whatsapp'

export const plugins: FrontendPlugin[] = [whatsapp]
