// SPDX-License-Identifier: Elastic-2.0

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	graph "github.com/gopherium/alphone/graph"
)

// newGraphRoot returns the core resolver root, no plugin extends the graph.
func newGraphRoot(core graph.ResolverRoot) graph.ResolverRoot {
	return core
}
